# config.yml
total_timesteps: 2_000_000
net_arch:
- 64
- 64
# activation_fn: 'nn.ReLU'
activation_fn: 'nn.Tanh'
share_feature: False
learning_rate: 1e-5
n_steps: 50
gamma: 0.9
gae_lambda: 1.0

estimator_kwargs:
  loops_per_train: 10
  vf_coef: 0.0
  ent_coef: 0.001
  max_grad_norm: 0.5

optimizer_kwargs:
  pseudo_population: 10000
  state_sd: 0.01
  obs_sd: 0.1
  alpha: 0.9

callback_kwargs:
  ensemble_size: 2000
  n_test: 200
  burn_in: 0.2
  eval_freq: 10000

env_kwargs:
  is_legal_action: True
  noise_sd: 0.1
  random_init: False