# config.yml
total_timesteps: 1_000_000
net_arch:
- 32
- 32
activation_fn: 'nn.ReLU'
learning_rate: 1e-5
train_every: 10
loops_per_train: 5
buffer_size: 10000
train_start: 1000
update_target_every: 10
batch_size: 100
exploration_fraction: 0.1
exploration_final_eps: 0.01

estimator_kwargs:
  cycle_len: 0
  sr_decay: 10000

optimizer_kwargs:
  pseudo_population: 10000
  prior_sd: 0.5
  obs_sd: 0.1
  alpha: 0.9
  sparse_sd: 0.05
  sparse_ratio: 0.5

callback_kwargs:
  ensemble_size: 3000
  n_test: 200
  sampling_threshold: 1
  burn_in: 0.1
  eval_freq: 10000